# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-alpina
# spec:
#   selector:
#     app: my-alpina
#   type: NodePort
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80

#     - name: ssh
#       protocol: TCP
#       port: 443
#       targetPort: 443